### ISSUE TITLE
Please update to the latest PMD version

### ISSUE THREAD

**Issue by WuggyX2** [ChuckJonas/vscode-apex-pmd#114]
**Is your feature request related to a problem? Please describe.**

PMD currently flags test methods that use the new Assert class introduced in api version 56.0. Support for this has been introduced in PMD version 6.49

**Describe the solution you'd like**
Update PMD to the latest version.

**Additional context**
![image](https://user-images.githubusercontent.com/51646225/197501900-1c44ca7c-2e48-40df-a628-8d36fe2cc875.png)

**Comment by frankpeleato-toast** [comment]
@ChuckJonas seeing this error on a daily basis. Any chance that we can update PMD to the current version?

**Comment by ChuckJonas** [comment]
I will try to get around to it when I have a moment.  In the meantime, you can download the latest version of PMD and configure the extension to use that instead `pmdBinPath`.  See the Readme for more details

**Comment by DougMidgley** [comment]
Suggest to wait for PMD 7 which should be coming in the coming months. Then just one update and good to go with quite a few deprecation related changes :)
