### ISSUE TITLE
Support for upcoming 7.0.0

### ISSUE THREAD

**Issue by rsoesemann** [ChuckJonas/vscode-apex-pmd#124]
@ChuckJonas  PMD 7 has come out as an RC and will soon be GA. There are a few changes that most probably make this plugin not work https://pmd.github.io/pmd/pmd_release_notes_pmd7.html#for-integrators

**Comment by adangel** [comment]
> Hi, while I try apex and i got this error
> 
> Analyzing extension-output-chuckjonas.apex-pmd-#1-Apex PMD PMD Command: java -cp "D:\Dowload\pmd-dist-7.0.0-rc3-bin\lib*;c:\Users\ACER\Desktop\demo*" net.sourceforge.pmd.PMD -f csv --no-cache -d "extension-output-chuckjonas.apex-pmd-#1-Apex PMD" -R "C:\Users\ACER\Desktop\demo\target\rules.xml" stderr:Error: Could not find or load main class net.sourceforge.pmd.PMD Caused by: java.lang.ClassNotFoundException: net.sourceforge.pmd.PMD
> 
> Failed Exit Code: 1

From https://github.com/ChuckJonas/vscode-apex-pmd/issues/34#issuecomment-1595775092
(cross referencing pmd/pmd#4598 pmd/pmd#4599)

**Comment by rsoesemann** [comment]
@adangel is there any alternative PMD Plugin we can use in VS Code that should also work with Apex and v7?

**Comment by rsoesemann** [comment]
Looking at older merged upgrade PMD PRs like it looks not like a lot to change https://github.com/ChuckJonas/vscode-apex-pmd/pull/93/files but

- Will @ChuckJonas merge then?
- Will PMD7 need bigger adjustments because there are some breaking changes
