### ISSUE TITLE
Public Feedback: Default Ruleset updates

### ISSUE THREAD

**Issue by ChuckJonas** [ChuckJonas/vscode-apex-pmd#138]
Looking for input on updates to the default ruleset.  This potentially impacts a lot of users (anyone who doesn't override it), so I want to have community consensus:

https://github.com/ChuckJonas/vscode-apex-pmd/blob/master/rulesets/apex_ruleset.xml

- Are there any rules that are missing?
- Are there any rules that should be removed?
- Any changes to `priority`?

Related PR:
- https://github.com/ChuckJonas/vscode-apex-pmd/pull/136
- https://github.com/ChuckJonas/vscode-apex-pmd/issues/113

**Comment by tomekduda** [comment]
My PR #113 was declined but in #112 I listed 1 more deprecated rule: `VariableNamingConventions`
Consider removing it? https://docs.pmd-code.org/pmd-doc-6.22.0/pmd_rules_apex_codestyle.html#variablenamingconventions and close my ticket?

And (shameless plug) there's a rule I'm using for scanning flows for SOQL/DML in a loop. It's very slow, I made it into a separate ruleset, I wouldn't add it to default without some clever improvements... but have a look? https://github.com/pmd/pmd/issues/3413#issuecomment-1264505445
I know there's https://github.com/Force-Config-Control/lightning-flow-scanner-vsce but I don't see it handling <strike>SOQL</strike> Get Records and calling actions in a loop

**Comment by ChuckJonas** [comment]
@tomekduda  I actually did not mean to close #13. Sorry. I must have checked it when I was cleaning out dependabot PR's.  Thank you for bringing that to my attention.

This does have a significant impact on user experience, so I'd like to come to some sort of community consensus. 

> And (shameless plug) there's a rule I'm using for scanning flows for SOQL/DML in a loop

That sounds like a great rule to have on hand for CI/CD or during an audit.  It would be cool to build a collection of these types of custom rules from the community.  If we add them [`rulesets`folder](https://github.com/ChuckJonas/vscode-apex-pmd/tree/master/rulesets) I think you could reference them in the config, or we could easily add a command to "Select a ruleset to run".

If you want to share it, please submit a PR!

**Comment by ChuckJonas** [comment]
I was over thinking this.  We should just go with the quick-start ruleset from PMD like you did in your #113 PR.  

I reopened it, but we should update it with the latest from PMD before we merge it.
