### ISSUE TITLE
Error executing PMD when project folder uses spaces

### ISSUE THREAD

**Issue by lexcraw4d** [ChuckJonas/vscode-apex-pmd#139]
**Describe the bug**
The bug is causing issues where it tells you the following error.
![image](https://github.com/ChuckJonas/vscode-apex-pmd/assets/71158947/cee0675f-599e-47be-8c81-d7828fe3833b)

**Apex PMD Output**
My settings are:
![image](https://github.com/ChuckJonas/vscode-apex-pmd/assets/71158947/8edd0285-ef22-40ca-adc0-b32161399d2f)
![image](https://github.com/ChuckJonas/vscode-apex-pmd/assets/71158947/49884989-afae-45b0-918a-b2d3b6870042)
![image](https://github.com/ChuckJonas/vscode-apex-pmd/assets/71158947/57f5a567-7f0b-4df1-a94d-c9c2a6555758)

**Apex PMD Settings**
I have applied to all workspaces/and user profile using the extension

- pmdPath: PMD 7.0.0-rc3 (I am in the process of clearing and removing to see if it will change - all worked fine yesterday) 
- rulesetPath: 

**Apex File**

All files it happens

**Screenshots**
see above
**Versions (please complete the following information):**
 - OS: Windows
 - vscode: 1.81.1

**Comment by ChuckJonas** [comment]
@lexcraw4d, did clearing `pmdBinPath` resolve the issue?
 
 Also, could you copy and paste the Output?  It's only showing a very small image. 
 
 Thanks

**Comment by ChuckJonas** [comment]
Also, if you're unable to fix it and blocked...

You can install the previous extension version by clicking the gear icon and then `install another version`.

<img width="634" alt="Menubar_and_index_ts_—_chat-demo_and_index_tsx_—_time-entry-service" src="https://github.com/ChuckJonas/vscode-apex-pmd/assets/5217568/abf6e8d8-09b2-4801-9e5b-6686de153cde">

**Comment by alvaroesqbae** [comment]
I am also facing this issue with the latest version.
```
stderr:Unrecognized option: -
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Failed Exit Code: 1
```

I have enabled the Show Std Out in the preferences and got the PMD command (I have ofuscated personal data)
```
Analyzing c:\Users\XXX\OfflineDocuments\Projects\Test - Project\force-app\main\default\classes\XXX.cls
PMD Command: c:\Users\XXX\.vscode\extensions\chuckjonas.apex-pmd-0.6.0\bin\pmd\bin\pmd check --no-progress -f csv --cache "c:\Users\XXX\OfflineDocuments\Projects\Test - Project/.pmdCache" -d "c:\Users\XXX\OfflineDocuments\Projects\Test - Project\force-app\main\default\classes\XXX.cls -R "c:\Users\XXX\.vscode\extensions\chuckjonas.apex-pmd-0.6.0\rulesets\apex_ruleset.xml"
```

When I run the exact same command in  CMD outside of VSCODE I get no error.

I have only faced this issue in project with a " - " in the folder name, so it might be related to it.

I am using Windows 10.
JRE 17 (openJDK).

Thanks!

**Comment by adangel** [comment]
I think, I found the culprit: the `workspaceRootPath` contains a space and we use this var to construct the classpath: https://github.com/ChuckJonas/vscode-apex-pmd/blob/bc306a3e7568c648142828875c49e21119b06af2/src/lib/apexPmd.ts#L138-L141

And that needs to be quoted as well.
I'm not adding the quotes in pmd.bat, because quoting under Windows is insane (a quote enables the quote flag, another quote disables it. When quote mode is on, delimiters are ignored. But adding a quote in vs-code-apex and in pmd.bat cancels it out...)

I'll create a PR later today.
