### ISSUE TITLE
Static Analysis Failed - Cannot load ruleset

### ISSUE THREAD

**Issue by NagarjunaParala** [ChuckJonas/vscode-apex-pmd#140]
Static Analysis Failed. Error Details: PMD Command Failed! Enable "Show StdErr" setting for more info.

**Comment by derrick-ejan-rs** [comment]
I am getting the same error using v0.6.0.  I have to roll back to version 0.5.9 for it to not error.

**Comment by adangel** [comment]
Do you have by any chance configured `pmdBinPath`? If so, please clear this setting.

https://github.com/ChuckJonas/vscode-apex-pmd/blob/bc306a3e7568c648142828875c49e21119b06af2/CHANGELOG#L10

**Comment by derrick-ejan-rs** [comment]
@adangel never set anything and its clear.  
![image](https://github.com/ChuckJonas/vscode-apex-pmd/assets/109308975/87a76ad0-1c9b-4da3-8ed6-26882cf3e222)

**Comment by adangel** [comment]
@derrick-ejan-rs thanks for the response. Then

> can you please Enable "Show StdErr" and copy the results from the output panel?

Without an error message there is nothing I can do to help you.

**Comment by adangel** [comment]
By the way: are you using windows, linux or macos?

**Comment by derrick-ejan-rs** [comment]
@adangel it actually has always been enabled for me.  In regards to the output panel I am not showing any output in that panel when that error occurs.

![image](https://github.com/ChuckJonas/vscode-apex-pmd/assets/109308975/11a69a1a-5052-4102-a762-2a914dc6c157)
![image](https://github.com/ChuckJonas/vscode-apex-pmd/assets/109308975/1ee7f009-b94f-42b6-8183-545bdda74a17)

**Comment by derrick-ejan-rs** [comment]
> By the way: are you using windows, linux or macos?

windows

**Comment by adangel** [comment]
You need to update your ruleset c:\Users\derrick.ejan\Documents\sfdx\pmd\ruleref.xml for PMD 7 - please refer to the changed rules here: https://docs.pmd-code.org/latest/pmd_release_notes_pmd7.html#-new-and-changed-rules

**Comment by derrick-ejan-rs** [comment]
> You need to update your ruleset c:\Users\derrick.ejan\Documents\sfdx\pmd\ruleref.xml for PMD 7 - please refer to the changed/removed rules here: https://docs.pmd-code.org/latest/pmd_release_notes_pmd7.html#-new-and-changed-rules

thanks yah just noticed that as well when seeing the output for the first time. I will give that a shot.

**Comment by ChuckJonas** [comment]
@adangel maybe we could parse `Cannot load ruleset` and display a more directed User error to let them know the issue is with their ruleset?

**Comment by adangel** [comment]
> @adangel maybe we could parse `Cannot load ruleset` and display a more directed User error to let them know the issue is with their ruleset?

Yes, that should be possible
