### ISSUE TITLE
PMD 6.55 broken while PMD 7 is not fully released

### ISSUE THREAD

**Issue by ethan-sargent** [ChuckJonas/vscode-apex-pmd#144]
**Describe the bug**
PMD 6.55 support has been deprecated before PMD 7 is fully released.
PMD 7 is still a release candidate, support for the latest fully released version should not be broken without a fully released PMD 7.

**Apex PMD Output**
Was passed main parameter "check" but no main parameter was defined.

**Apex PMD Settings**
PMDBinPath set to 6.55

- pmdBinPath: path/to/6.55
- rulesets: custom
- additionalClassPaths: N/A

**Apex File**

**Screenshots**

**Versions (please complete the following information):**
 - OS: all
 - vscode: latest

**Comment by ChuckJonas** [comment]
If you want to continue to run PMD6, please manually install the `0.5.9` version of the extension:

<img width="608" alt="Menubar_and_createSupportTicket_ts_—_chat-demo_and_Extension__Git_Extension_Pack_—_salesforce-audit" src="https://github.com/ChuckJonas/vscode-apex-pmd/assets/5217568/c071c820-999f-4d17-9b6c-cf0e26f94f4f">

**Comment by DougMidgley** [comment]
Rather annoying, in that we cannot provide guidance to teams cannot be provided recommendations for a specific version https://github.com/microsoft/vscode/issues/138048
