### ISSUE TITLE
The VS code plugin does not detect VF related flaws

### ISSUE THREAD

**Issue by smo17** [ChuckJonas/vscode-apex-pmd#15]
The VS code integrated plugin does not detect following VF flaws even if specified in xml rule set:
VfUnescapeEl
VfCsrf

[http://pmd.sourceforge.net/snapshot/pmd_rules_vf_security.html
](url)
Note that running the same rule set via PMD command line does show issues in VF if exist

**Comment by nchursin** [comment]
Sorry for such a long response, I'll take a look, thanks for reporting this

**Comment by nchursin** [comment]
@smo17 the issue is right now the plugin doesn't analyze VF at all, only apex. Will add this ability

**Comment by ChuckJonas** [comment]
@nchursin does apex PMD actually support analyzing VF pages?  If so, it shouldn't be hard to add.

**Comment by nchursin** [comment]
@ChuckJonas yes, I checked that. I'll finally have time to dig into this and #5 this weekend

**Comment by ChuckJonas** [comment]
It does appear that they do have _something_ for visualforce... however, it currently only has two rules, so I'm not sure it's worth the effort.  

https://pmd.github.io/latest/pmd_rules_vf.html
