### ISSUE TITLE
Register at https://open-vsx.org/extension/ for use with Code Builder

### ISSUE THREAD

**Issue by rsoesemann** [ChuckJonas/vscode-apex-pmd#155]
@ChuckJonas you might have seen it; [Salesforce announed Code Builder](https://developer.salesforce.com/blogs/2023/10/salesforce-code-builder-is-now-generally-available?utm_campaign=amer_sfld&utm_source=linkedin&utm_medium=organic_social&utm_content=Salesforce+Developers_) and [only Extensions registered here](https://www.linkedin.com/feed/update/urn:li:activity:7122624631542317056?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7122624631542317056%2C7122631791500255232%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A7122624631542317056%2C7122634369957072896%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287122631791500255232%2Curn%3Ali%3Aactivity%3A7122624631542317056%29&dashReplyUrn=urn%3Ali%3Afsd_comment%3A%287122634369957072896%2Curn%3Ali%3Aactivity%3A7122624631542317056%29) are usable in Code Builder. I think Apex PMD should be there. ;-)

**Comment by adangel** [comment]
I've created the namespace pmd : https://open-vsx.org/namespace/pmd and trying to claim it (see https://github.com/EclipseFdn/open-vsx.org/issues/2164)

Published the last version of vscode-apex-pmd there - note: the publisher is now "pmd" on open-vsx and "chuckjonas" on vscode marketplace, which requires currently a manual change in package.json.

The extension is now available on open-vsx: https://open-vsx.org/extension/pmd/apex-pmd

**Comment by adangel** [comment]
We can add the following badges to the readme:

![Open VSX Version](https://img.shields.io/open-vsx/v/pmd/apex-pmd)
![Open VSX Downloads](https://img.shields.io/open-vsx/dt/pmd/apex-pmd)

```
![Open VSX Version](https://img.shields.io/open-vsx/v/pmd/apex-pmd)
![Open VSX Downloads](https://img.shields.io/open-vsx/dt/pmd/apex-pmd)
```

And we should automate the publishing to open vsx (see #153)

**Comment by rsoesemann** [comment]
Thanks @adangel I didn't know that you can do this on behalf of @ChuckJonas. Did you guys agree that PMD is taking over this repo?
