### ISSUE TITLE
PMD detected "problems" do not show up in VS code window.

### ISSUE THREAD

**Issue by ShriPunta** [ChuckJonas/vscode-apex-pmd#16]
**Steps to replicate**:
1) Download PMD zip; set environment variable to the path
2) Download Tools for Apex in VS Code
3) Download JDK 8 especially for Apex code plugin and override the variable:
"salesforcedx-vscode-apex.java.home":"<path>"
4) Download Apex PMD in VS Code:

Get the following **error** in "Output" tab:

PMD Command: java -cp "C:\Users\shrip\Downloads\Softwares\pmd-bin-6.4.0\bin\lib\*" net.sourceforge.pmd.PMD -d "c:<path>\..\<classname>.cls" -f csv -R "c:\Users\shrip\.vscode\extensions\chuckjonas.apex-pmd-0.1.0\rulesets\apex_ruleset.xml"
error:Error: Command failed: java -cp "C:\Users\shrip\Downloads\Softwares\pmd-bin-6.4.0\bin\lib\*" net.sourceforge.pmd.PMD -d "<path>\..\<classname>.cls" -f csv -R "c:\Users\shrip\.vscode\extensions\chuckjonas.apex-pmd-0.1.0\rulesets\apex_ruleset.xml"
Error: Could not find or load main class net.sourceforge.pmd.PMD
Caused by: java.lang.ClassNotFoundException: net.sourceforge.pmd.PMD

stdout:
stderr:Error: Could not find or load main class net.sourceforge.pmd.PMD
Caused by: java.lang.ClassNotFoundException: net.sourceforge.pmd.PMD

Am I doing anything wrong?

**Comment by ShriPunta** [comment]
Apologies for raising it as an issue.

This was resolved by copying the "lib" folder inside the "bin" folder.

**Comment by avandelRLS** [comment]
I just encountered the same issue in the latest version, 0.2.2, for some reason it doesnt lift the pmd-core jar upon the cp key

**Comment by nchursin** [comment]
@avandelRLS looks like it's a documentation issue for the plugin. Take a look at #32 
I'll update docs and will release a new version
