### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by Telarian** [ChuckJonas/vscode-apex-pmd#3]
I've been trying to get this extension working. I know it's doing something because at first it would throw errors telling me it couldn't find ApexPMD. I can get it to throw that error by messing up the user setting, so it seems like it's activating. I also know ApexPMD works fine because I can run it successfully from the command line, but I just get absolutely no response when I tell the extension to analyze a file in vsCode.

Do you have any advice on obvious things I could be doing wrong?

Any assistance would be greatly appreciated.
Thanks

**Comment by ChuckJonas** [comment]
**Couple questions:**

So when you run it from the command line it returns "Problems" correctly?  

Are you running the default Ruleset?     
```
"apexPMD.useDefaultRuleset": "true",
"apexPMD.rulesetPath": "",
```

Are you running Windows or Mac?

**Comment by Telarian** [comment]
Indeed, it turned them into a nice little html page for me which was handy in the mean time.

I have tried both running with the default (with the settings you show) as well as I have downloaded the default ruleset and tried it with that. Either way does nothing though.

I'm running Windows.

**Comment by ChuckJonas** [comment]
Ah yes...  I haven't yet tested this on Windows...  Theres likely something wrong with the way I'm building the path.  I'll try to boot up a vm in the next couple days and see if I can get it working

**Comment by Telarian** [comment]
Ah, ok. Cool.

Thanks for looking into it. If you figure it out, I would be happy to hear about it.

**Comment by ChuckJonas** [comment]
@Telarian I just pushed an update that should have made my paths work for multi-platform, but I don't have windows to test.  Can you update the plugin and see if it now works?

**Comment by Telarian** [comment]
I tried it. I'm afraid I don't think it fixed anything. It's kind of hard to know what's going on with it because it just silently fails. But when I choose the option "Apex Static Analysis: On File" nothing happens.

**Comment by ChuckJonas** [comment]
Damn... thanks for trying!  I definitely need to improve the error handling.

Going to boot up a windows VM and see if I can reproduce it.

**Comment by ChuckJonas** [comment]
@Telarian I added a debug channel!  When you get a chance, update the extension and run `Apex Static Analysis: Show Debug Output`.  Try to run it on a file and attach the output here

**Comment by Telarian** [comment]
Well, that definitely gives me more feedback to provide. ;)
Here is the output of that:

PMD Command: java -cp "C:\DirExes\ApexPMD\lib\*" net.sourceforge.pmd.PMD -d "c:\Dev\Salesforce\primary\src\classes\Opportunities_Tests.cls" -f csv -R "C:\Users\telar\.vscode\extensions\chuckjonas.apex-pmd-0.0.21\rulesets\apex_ruleset.xml"
error:null
stdout:"Problem","Package","File","Priority","Line","Description","Rule set","Rule"

stderr:Dec 08, 2016 8:33:44 PM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA23_transition. Found 7927114 shorts which is 15MB not including array overhead. Removed 7204963 shorts which is 13MB not counting array overhead. Took 16ms.

TypeError: Cannot read property 'substr' of undefined

**Comment by ChuckJonas** [comment]
@Telarian nice! It looks like it actually processed the command.  `TypeError: Cannot read property 'substr' of undefined` is actually the current expected behavior when there are no "Problem" results.

**Try to run it on this class:** 

```java
public class fooBar{
	public fooBar() {
		for(Integer i = 0; i < 5; i++){
			insert new Account();
		}
	}
}
```

You should see two problems.  

**Note:** I've noticed that some of the rules don't seem to be working... I'm not sure if this is a problem with the ruleset I'm running or PMD in general.

**Comment by Telarian** [comment]
Ah yes. It appears to be working now. Ha! I had forgotten to make sure I had a problem in my test class. It would be good if it could put some sort of indicator in the status bar or some such thing to let you know it had run. Thanks so much for all your hard work. This is awesome and I'm very excited to have it.

**Comment by ChuckJonas** [comment]
Awesome! 

ya definitely still lots of room for improvement (feel free to create an issue for that feature request).  Thanks for the feedback.

**Comment by kogino** [comment]
I specify the file path as follows and close the editor. After that, when I restarted the editor, I did not get an error and it was available.
"apexPMD.pmdPath": "C:\\Users\\xxx\\pmd-bin-5.8.1"
