### ISSUE TITLE
Method names should not contain underscores... but, what about test method names?

### ISSUE THREAD

**Issue by SalesforceBobLightning** [ChuckJonas/vscode-apex-pmd#33]
RE warning "Method names should not contain underscores"

I would be great if this warning did not appear if a method is marked as 'testMethod' or '@isTest'

Because using underscores in unit test method names is a common practice to make them readable.

Thoughts?

**Comment by ChuckJonas** [comment]
@SalesforceBobLightning this project is really just an execution wrapper for [pmd](https://github.com/pmd/pmd).

Anything related to the actually static analysis of the code would need to happen there.
