### ISSUE TITLE
APEX PMD error

### ISSUE THREAD

**Issue by npathuri0531** [ChuckJonas/vscode-apex-pmd#34]
**Describe the bug**
I am using Macbook Pro. APEX PMD is always giving me the error 
"**Static Anaylsis Failed. Error Details: PMD Command Failed. Enable "Show StdErr" setting for more info.**" I have configured everything correctly but not sure why the error.  I have also configured the java in the path variable. When I do echo $PATH, I get

/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/1.6.0.jdk

**Apex PMD Output**
"Static Anaylsis Failed. Error Details: PMD Command Failed. Enable "Show StdErr" setting for more info."

Though showStdErr is enabled, it is still not showing anything correctly.

**Apex PMD Settings**
User Settings:
{
    "apexPMD.runOnFileOpen": true,
    "files.trimFinalNewlines": true,
    "apexPMD.priorityWarnThreshold": 3,
    "apexPMD.pmdBinPath": "/Users/chaitp/Documents/pmd-bin-6.10.0",
    "salesforcedx-vscode-apex.java.home": "/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home",
    "apexPMD.showStdOut": true,
    "apexPMD.showStdErr": true,
    "git.autofetch": true,
    "git.enableSmartCommit": true
}

WorkSpace Settings:

{
    "terminal.integrated.env.osx": {
        "SFDX_SET_CLIENT_IDS": "sfdx-vscode"
    },
    "terminal.integrated.env.linux": {
        "SFDX_SET_CLIENT_IDS": "sfdx-vscode"
    },
    "terminal.integrated.env.windows": {
        "SFDX_SET_CLIENT_IDS": "sfdx-vscode"
    },
    "apexPMD.pmdBinPath": "/Users/chaitp/Documents/pmd-bin-6.10.0",
    "apexPMD.runOnFileOpen":true,
    "apexPMD.showStdOut": true,
    "apexPMD.showStdErr": true,
    "salesforcedx-vscode-apex.java.home": "/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home"
}

- pmdPath: /Users/chaitp/Documents/pmd-bin-6.10.0

- rulesetPath: None

**Apex File**

**Screenshots**

**Versions (please complete the following information):**
 - OS: macOS High Sierra, Version 10.13.6

 - vscode: Version 1.30.2 (1.30.2)

**Comment by npathuri0531** [comment]
<img width="488" alt="screen shot 2019-01-15 at 8 35 53 pm" src="https://user-images.githubusercontent.com/12927003/51226814-096ac080-1906-11e9-84a8-d324d5a7fcba.png">

**Comment by nchursin** [comment]
Hi
After enabling `showStdErr` setting please open output console and switch to `Apex PMD` in the picklist on the right
![image](https://user-images.githubusercontent.com/8916229/51232221-212e5d00-1977-11e9-915f-7db636c396b1.png)
This console will show you the actual error. Post it here, so we can troubleshoot further

**Comment by npathuri0531** [comment]
Thanks Nikita..Here is the error.

Analysing /Users/chaitp/Documents/Salesforce VSCode/src/classes/TRN_SurgeonTrainingSchedulerController.cls
PMD Command: java -cp "/Users/chaitp/Documents/pmd-bin-6.10.0/lib/*" net.sourceforge.pmd.PMD -d "/Users/chaitp/Documents/Salesforce VSCode/src/classes/TRN_SurgeonTrainingSchedulerController.cls" -f csv -R "/Users/chaitp/.vscode/extensions/chuckjonas.apex-pmd-0.2.2/rulesets/apex_ruleset.xml"
stderr:Exception in thread "main" 
stderr:java.lang.UnsupportedClassVersionError: net/sourceforge/pmd/PMD : Unsupported major.minor version 51.0

stderr:	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)

stderr:	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)

stderr:	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)

stderr:	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)

stderr:	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)

stderr:	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
stderr:
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)

stderr:	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)

stderr:	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)

stderr:	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by npathuri0531** [comment]
@nchursin Thanks so much Nikita. I had installed jdk 1.6 and now I upgraded to 1.8 and also installed JRE 8. The issue is resolved. Thanks again.

**Comment by Saransarveshmk** [comment]
Hi,
While I am trying Apex Code. I got this error from APEX PMD
 Static Analysis Failed. Error Details: PMD Command Failed! Enable "Show StdErr" setting for more info.
Can anyone help me out with this

**Comment by adangel** [comment]
@Saransarveshmk 
Please enable the extension setting "Show Std Err" (if not already enabled):
![image](https://user-images.githubusercontent.com/1573684/222372285-0acbd3b4-f15a-41f7-9b60-b6d47ea52485.png)
Then run it again and share the error message from the output console. See https://github.com/ChuckJonas/vscode-apex-pmd/issues/34#issuecomment-454675739 for details how to show the output from Apex PMD:

> After enabling `showStdErr` setting please open output console and switch to `Apex PMD` in the picklist on the right
> 
![image](https://user-images.githubusercontent.com/1573684/222373251-27228a83-09f6-4af4-ac5c-e837f6e91453.png)
> This console will show you the actual error.

With the concrete error message, please open then a new issue (this one is closed and solved already)

**Comment by phucnl2003** [comment]
Hi, while I try apex and i got this error

Analyzing extension-output-chuckjonas.apex-pmd-#1-Apex PMD
PMD Command: java -cp "D:\Dowload\pmd-dist-7.0.0-rc3-bin\lib\*;c:\Users\ACER\Desktop\demo\*" net.sourceforge.pmd.PMD -f csv --no-cache -d "extension-output-chuckjonas.apex-pmd-#1-Apex PMD" -R "C:\Users\ACER\Desktop\demo\target\rules.xml"
stderr:Error: Could not find or load main class net.sourceforge.pmd.PMD
Caused by: java.lang.ClassNotFoundException: net.sourceforge.pmd.PMD

Failed Exit Code: 1

**Comment by Shailendra859** [comment]
Hi I got this error
Analyzing d:\Perman\perman-phase-III\force-app\main\default\classes\AppraisalLetterTriggerHelper_Test.cls
stderr:'c:\Users\Shailendra' is not recognized as an internal or external command,
operable program or batch file.
