### ISSUE TITLE
Ignore classes in `.sfdx` folder.

### ISSUE THREAD

**Issue by ntotten** [ChuckJonas/vscode-apex-pmd#36]
**Is your feature request related to a problem? Please describe.**
When you run `Apex Static Analysis: On Workspace` the files generated by the SF Apex extension that are in `.sfdx/tools/sobjects/...` get scanned.

**Describe the solution you'd like**
Since `.sfdx` is only for generated/non-user files, this folder should always be ignored.

**Comment by ChuckJonas** [comment]
hmmm, yes....

Right now we are just passing the entire workspace folder to our [java pmd cmd](https://github.com/ChuckJonas/vscode-apex-pmd/blob/master/src/lib/apexPmd.ts#L118).

Without somehow explicitly knowing the workspace structure, I think the best I can do is just filter out the results from the .sfdx path.   

This could cause performance issues (although I don't think it's expected that this command executes quickly anyways).  Worse, this might actually compound impacts of issue #38.

**Comment by ChuckJonas** [comment]
The alternative would be to do our own parsing of the file system to determine target files and use the [-filelist](https://pmd.github.io/pmd-6.7.0/pmd_userdocs_cli_reference.html) flag...  Could get messy

**Comment by ChuckJonas** [comment]
nvm, it appears you can just ignore files via the ruleset! 

`<exclude-pattern>.*/.sfdx/.*</exclude-pattern>`

Fixed
