### ISSUE TITLE
Exit code of 143 and results being truncated

### ISSUE THREAD

**Issue by ChuckJonas** [ChuckJonas/vscode-apex-pmd#38]
**Describe the bug**
If I run `on Workspace` with a really large project, I'm getting an exit code of 143 in the [on exit handler](https://github.com/ChuckJonas/vscode-apex-pmd/blob/master/src/lib/apexPmd.ts#L135), and a truncated result.  From what I can find online, [this might be the OS is sending sigterm?!](https://stackoverflow.com/questions/6963811/jvm-returns-error-143)  Following the [PMD documentation,](https://pmd.github.io/latest/pmd_userdocs_cli_reference.html#exit-status) were only displaying an error message to the user on a exit code of `1`.

Oddly enough, if I run the exact same `cmd` via command line, it completes without issue.

Unfortunately, the csv parser crashes fully when this happens.  

If we can't figure out the source, we should at least try to parse what valid csv data we did receive, and display a message some some errors were not successfully parsed.

**Versions (please complete the following information):**
 - OS: OSX
 - vscode: 1.31.0

**Comment by nchursin** [comment]
Is this fixed with csv package upgrade?

**Comment by ChuckJonas** [comment]
@nchursin unfortunately no, the error is happening in the execution of the pmd jar...  However, in the 3.2 branch I did add [some code to recover and display as many records as we can](https://github.com/ChuckJonas/vscode-apex-pmd/blob/b767a447663ab2ad63c9a8ea564d468cc5c28aee/src/lib/apexPmd.ts#L161).


For example, when it was failing on my machine, it was happening around the 700-800 record range.  If the CSV parsing fails, I'm just dropping the last record (typically a partial line) and trying again. 

It would probably be good to also warn the user something along the lines of "Not all errors have been displayed"

**Comment by ChuckJonas** [comment]
Fixing #36 cause this error to no longer happen in my problem project.  

I still think it's possible that this comes up in a REALLY large project, but at least we handle it as gracefully as possible now.

Going to leave this one open though, as the root issue is not identified or fixed.

**Comment by nawforce** [comment]
I was testing on a ~500 kLOC project & hit this. The issue appears to be with the default maxBuffer setting for ChildProcess.exec(). The the node docs say:

'Largest amount of data in bytes allowed on stdout or stderr. If exceeded, the child process is terminated and any output is truncated. See caveat at maxBuffer and Unicode. Default: 1024 * 1024' with the default signal for termination being SIGTERM.

I increased this to 10MB and then pmd rans to completion on this project. Although this is an easy fix I think there might be some overhead from the existing output handling on large projects. I have access to a larger project so will do some testing on that to see if there is any time to be saved in a workspace scan.
