### ISSUE TITLE
Remove code climate properties from default ruleset

### ISSUE THREAD

**Issue by ChuckJonas** [ChuckJonas/vscode-apex-pmd#47]
Currently, all of our rules include the code climate attributes (`cc_X`):

```
   <rule ref="category/apex/bestpractices.xml/ApexUnitTestClassShouldHaveAsserts" message="Apex unit test classes should have at least one System.assert() or assertEquals() or AssertNotEquals() call">
      <priority>3</priority>
      <properties>
         <!-- relevant for Code Climate output only -->
         <property name="cc_categories" value="Bug Risk" />
         <property name="cc_remediation_points_multiplier" value="100" />
         <property name="cc_block_highlighting" value="false" />
      </properties>
   </rule>
```

These have been depreciated, aren't being used by our library and add a lot of bloat to the ruleset.  

I think they should be removed. 

It's also worth noting that PMD now includes a [default apex ruleset ](https://pmd.github.io/pmd-6.13.0/pmd_release_notes.html#quickstart-ruleset-for-apex) itself... However one advantage to maintaining our own is that we can exclude the `.sfdx` folder which is important for projects using `sfdx` format

**Comment by ChuckJonas** [comment]
@nchursin just wanted to get your thoughts before I rip out the `cc_` properties... Can you think of any reason they should be there?

**Comment by nchursin** [comment]
Not really. I mean in case someone uses older versions of PMD for some reason, they still can add those to a custom ruleset
