### ISSUE TITLE
runOnFileOpen / runOnFileSave doesn't execute

### ISSUE THREAD

**Issue by smasala** [ChuckJonas/vscode-apex-pmd#52]
Following settings (in any combination) have no effect when you open or save a java file.
```
"apexPMD.runOnFileOpen": true,
"apexPMD.runOnFileSave": true,
"editor.codeActionsOnSave": {
      "apex-pmd.runFile": true
},
```

Static analysis only works when manually triggering the action (via `CTRL + SHIFT + P -> Apex Statis Analysis: On File`)

**VSCode:** `1.34.0`

**Comment by ChuckJonas** [comment]
does anything show up in the extensions output panel?

**Comment by smasala** [comment]
No, only when you trigger it manually.

**Comment by ChuckJonas** [comment]
What operating system?

**Comment by smasala** [comment]
Windows 7

**Comment by ChuckJonas** [comment]
You said java file... Did you mean Apex Class (`.cls`)?  

This extension is for salesforce Apex language only.   The filename must end in `.cls` for this extension to run on save

**Comment by smasala** [comment]
That would explain it :+1 any plans to support `java` on save? PMD does support it after all.

**Comment by ChuckJonas** [comment]
@smasala this extension is JUST meant to be for running PMD against the salesforce apex language...  The fact that you can even run it against java at all is actually a minor bug.

I've thought of generalizing it (as 95% of the code would work as is for any pmd language), but honestly, I have too many open source projects as is at them moment, and that opens up this up to a whole new audience of people with potential issues to support.
