### ISSUE TITLE
Issue setting pmdPath

### ISSUE THREAD

**Issue by TeamTeaTime** [ChuckJonas/vscode-apex-pmd#6]
I'm on MacOS 10.12. I installed pmd with homebrew (pmd version 5.5.2) so it is in my path at /usr/local/bin/pmd.

I edited settings.json to reflect this:
`    "apexPMD.pmdPath": "/usr/local/bin/pmd", `

When I open an apex class file I get the error "PMD Path not set. Please see Installation Instructions."

Any idea what I'm doing wrong?

**Comment by ChuckJonas** [comment]
what is returned when you run `brew info pmd`. `"apexPMD.pmdPath"` does not point to the location of the pmd executable, but instead the path to the install folder (I'm not sure how brew handles packaging).  

The structure under the target folder should look something like this:
<img width="273" alt="jonas" src="https://cloud.githubusercontent.com/assets/5217568/22449663/ca996066-e71e-11e6-83a8-7d16523b4e3f.png">

**Comment by TeamTeaTime** [comment]
```brew info pmd
pmd: stable 5.5.3 (bottled)
Source code analyzer for Java, JavaScript, and more
https://pmd.github.io
/usr/local/Cellar/pmd/5.5.2 (51 files, 65.7M) *
  Poured from bottle on 2017-01-23 at 12:15:45
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pmd.rb
==> Dependencies
Build: maven ✔
==> Requirements
Required: java >= 1.8 ✔
==> Caveats
Run with `pmd` (instead of `run.sh` as described in the documentation).
```

It looks like the folder exists at /usr/local/Cellar/pmd/5.5.2/libexec . It works if I set my pmdPath and then actually quit VSCode. It didn't work with just reloading the window.

I went ahead and grabbed the binaries from the link in your readme and put them in /Users/<username>/bin/pmd, and that worked as well, also requiring restarting the entire app. 

Thanks for your help!

**Comment by ChuckJonas** [comment]
That makes sense.  Currently, User Settings are loaded when the project window is initiated... There's probably a better way to do this, or at least detect updates.

Let me know if you have any other feedback/suggestions on how to improve this extension
