### ISSUE TITLE
Switch statements

### ISSUE THREAD

**Issue by Libertha** [ChuckJonas/vscode-apex-pmd#61]
Currently the extension doesn't seem to know what to do with the summer '18 switch statements.

it will just throw no viable alternative warnings and mismatched inputs.

If this would be updated, that'd be amazing!

**Comment by ChuckJonas** [comment]
@rsoesemann I feel like I saw something a while back that you guys might have fixed this in a recent release?

May be as simple as just updating the pmd jar.

@Libertha otherwise, you'll want to submit this issue against the [PMD repo](https://github.com/pmd/pmd)

**Comment by rsoesemann** [comment]
@ChuckJonas I thought we added switch long ago. Let me check that.

**Comment by ChuckJonas** [comment]
We may have just been running a old version

**Comment by rsoesemann** [comment]
@ChuckJonas / @Libertha thanks for pointing this out. We indeed had no full support for switch in pmd. It just was added and will be released in 6.22. Go here to track it https://github.com/pmd/pmd/issues/2306
