### ISSUE TITLE
unable to disable or uninstall apex pmd in vscode

### ISSUE THREAD

**Issue by vorzap** [ChuckJonas/vscode-apex-pmd#62]
Hello I have grown tired of seeing stupid problems like variable doesn't exist hundreds of times even though it clearly does. Because seeing hundreds of problems with every apex file I work with is very distracting, I am trying to disable pmd. I have tried removing the plugin but still get hundreds of pmd warnings. I reinstalled the plugin and disabled all the run options and it still runs all the time. Is there anyway I can get this thing to shut up already?

**Comment by ChuckJonas** [comment]
Uninstalling/disabled and reloading the project will clear all the "problems".  Once the extension is uninstalled/disabled, there is no way they could possibly come back.

I think you are most likely confused.   I'm guessing the errors are coming from a different source (I'm not aware of a "variable doesn't exist" rule). 

All apex PMD errors will be tagged with `apex-pmd` as shown below. 

<img width="790" alt="" src="https://user-images.githubusercontent.com/5217568/62891251-790d2680-bd02-11e9-9615-b386f2e4141b.png">

If I am mistaken, and for some reasons you are still seeing `apex-pmd` errors after uninstalling & reloading, feel free to reopen this issue.

**Comment by vorzap** [comment]
My mistake. This was actually the sfdx semantic error checking feature. Sorry about the erroneous issue.
