### ISSUE TITLE
Ability to export the results from PMD

### ISSUE THREAD

**Issue by Harmeet2019** [ChuckJonas/vscode-apex-pmd#63]
Issue Type: <b>Feature Request</b>

Hi Team,
It is essential that we are able to download or extract the report from PMD so that it can be shared when working in a shared environment.
Would like to hear back from you if my opinion is considered.

Regards,
Harmeet

Extension version: 0.4.4
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.16299

**Comment by ChuckJonas** [comment]
Duplicate of https://github.com/ChuckJonas/vscode-apex-pmd/issues/59
