### ISSUE TITLE
Specify pmdBinPath as a relative path

### ISSUE THREAD

**Issue by mcartoixa** [ChuckJonas/vscode-apex-pmd#64]
PMD is updated quite regularly and it is quite painful to synchronize everyone (including the CI server) on which version is used on which project. I have build scripts that can download the right version of PMD for the project before building it and performing the analysis.

What I miss is the ability to make the developers use this version in a seamless manner, which would be to specify `pmdBinPath` as a path relative to a project in the local `settings.json`.

What do you think?

**Comment by ChuckJonas** [comment]
I'm actually surprised this doesn't work...

As you can [see here](https://github.com/ChuckJonas/vscode-apex-pmd/blob/master/src/lib/apexPmd.ts#L157), `pmdPath` is just being used when building the class paths for the java command.

I can't think of any reason a [relative class path](https://stackoverflow.com/questions/16502663/java-classpath-and-relative-paths) wouldn't work here (as long as it is in fact formatted as a relative path).

Can you post the `settings.json` which you've tried with?

**Comment by ChuckJonas** [comment]
interesting... that would be coming from the [check here](https://github.com/ChuckJonas/vscode-apex-pmd/blob/master/src/lib/apexPmd.ts#L282), which basically just calls:

```
let stat = fs.statSync(filePath);
return stat.isDirectory();
```

I can try to reproduce a some point in the near future.  Or if you are feeling adventurous, you could clone this project down, `npm install` and try to debug whats happening on those lines above (it may require more steps than that if your not setup for node dev).

**Comment by dangmai** [comment]
So I've run into this, and the issue is that VSCode sets the current working directory to my home directory (i.e. `/home/dangmai`), and your call to statSync is relative to that directory, instead of the workspace root. Also, `${workspaceRoot}` is not being expanded to the actual location, so that doesn't work either.

**Comment by dangmai** [comment]
I opened a PR to fix this issue: https://github.com/ChuckJonas/vscode-apex-pmd/pull/67 That's not the only way to fix this, but feel free to merge if you think you like the approach.
