### ISSUE TITLE
Support for Java Source Static analysis

### ISSUE THREAD

**Issue by wtsiamruk** [ChuckJonas/vscode-apex-pmd#66]
Can the tool be used to perform analysis on java source code files?
If no, is there any plans to introduce such capability?

**Comment by ChuckJonas** [comment]
this extension is just built for Salesforces apex. 

It could easily be forked, modified and released as a new extension to run for java, but I have no plans to do so. 

More or less you would just need to update a few places to target java files instead of apex.

**Comment by wtsiamruk** [comment]
@ChuckJonas ok, thank you :)
