### ISSUE TITLE
Priority change for rules

### ISSUE THREAD

**Issue by Puneet1726** [ChuckJonas/vscode-apex-pmd#68]
Hi,

Currently I am using Apex PMD with VSCode which has inbuilt priority for the rules.
I want to change the priority according to our need.

Can I change the priority locally? If yes, please let me know the path.
Else let me know how to proceed on this

**Comment by ChuckJonas** [comment]
you can set the rule priority (integer number) via your ruleset.xml.

You can also set the threshold for which rule priority's trigger errors or warnings in vscode, via the extension settings. 

See `priorityErrorThreshold` & `priorityWarnThreshold` in the readme.

**Comment by Puneet1726** [comment]
Hi @ChuckJonas 

Thanks for the information.

Can I see the priority details for each error in problem output?
Currently its not showing the property details in the output.
![image](https://user-images.githubusercontent.com/26565880/70027301-d84fb900-15c7-11ea-8711-146bf2281e53.png)

Thanks,
Puneet
