### ISSUE TITLE
PMD Apex doesn't seem to run with latest VS Code Update

### ISSUE THREAD

**Issue by amsecada** [ChuckJonas/vscode-apex-pmd#7]
With the latest update of the VS Code core I downloaded this morning, I noticed all my .cls files were not linting on file open, nor on save. I checked my PMDPath variable and see that it resolves. I verified this because when I removed the directory, I received an Error from the Extension saying that I had not configured it correctly, and this error message vanishes when I place the directory back into the PMDPath Variable.

For now, I will be uninstalling and downgrading my VS Core back to the previous release to see if this could work as a workaround, but thought I would bring to your attention.

Thanks!

**Comment by ChuckJonas** [comment]
interesting... I recently noticed a similar issue with my apex debug extension.  I don't personally use this extension anymore but if people are still using it I can look into upgrading it... I imagine it's probably something simple.

**Comment by ChuckJonas** [comment]
@amsecada could you possibly give me the exact error message you came across?

**Comment by amsecada** [comment]
Hey Chuck -- Thanks for your quick response.

I don't have an exact error message for you, but to help out as much as I could I did a quick screen record session of what I'm seeing. If you'd like me to click somewhere to get you a stacktrace / whatever else you would need on your end to examine, please let me know and I'm happy to help.

Thanks!

https://drive.google.com/drive/folders/0B3YOfADFxIuyS2I5RjlnaHBTMUU

**Comment by nchursin** [comment]
Hey @amsecada 
First of all, try using `\\` instead of `/` in path. It's some Windows vs Unix paths
If the issue persists please use the `Show Debug Output` command to provide some more info on the error, thanks!
