### ISSUE TITLE
Broken link in VS Code Marketplace

### ISSUE THREAD

**Issue by spottedmahn** [ChuckJonas/vscode-apex-pmd#71]
**Describe the bug**
On https://marketplace.visualstudio.com/items?itemName=chuckjonas.apex-pmd

![image](https://user-images.githubusercontent.com/14079228/75272502-0bbb7180-57cc-11ea-850f-8f81a938de49.png)

which points to https://pmd.sourceforge.io/snapshot/pmd-apex/

![image](https://user-images.githubusercontent.com/14079228/75272542-21309b80-57cc-11ea-9c7e-6bba13573bb2.png)

**Comment by ChuckJonas** [comment]
fixed. Thanks!

**Comment by spottedmahn** [comment]
looks good, thanks!

![image](https://user-images.githubusercontent.com/14079228/77019475-01b60a00-6957-11ea-9490-2b93a4fcf49e.png)
