### ISSUE TITLE
Chinese encode problem

### ISSUE THREAD

**Issue by rectcircle** [ChuckJonas/vscode-apex-pmd#74]
**Describe the bug**

Chinese encode problem

![image](https://user-images.githubusercontent.com/18106246/77560057-e2d7ea80-6ef7-11ea-89ab-8f1bc3efaffe.png)

 - OS: OSX 10.15.3 (19D76)
 - vscode: 1.43.2

Read this repo code and debug, I find a solution:

`src/lib/apexPmd.ts` :161

```ts

        const cmd = `java -Dfile.encoding=utf-8 -cp "${classPath}" net.sourceforge.pmd.PMD ${pmdKeys}`;

        if (this._showStdOut) this._outputChannel.appendLine('PMD Command: ' + cmd);

        let pmdCmd = ChildProcess.exec(cmd,
            {
                encoding: 'UTF-8',
                maxBuffer: Math.max(this._commandBufferSize, 1) * 1024 * 1024
            });
```

![image](https://user-images.githubusercontent.com/18106246/77560107-f71be780-6ef7-11ea-96bc-50f0346f576b.png)

I do n’t have a windows PC, so I ca n’t test Windows, so I did n’t mention Pull Merge

**Comment by ChuckJonas** [comment]
Could you zip and upload a project so I can reproduce?

**Comment by rectcircle** [comment]
> Could you zip and upload a project so I can reproduce?

@ChuckJonas  It seems impossible to reproduce the issue. 😂  see the zip file

[apex-pmd-java-test.zip](https://github.com/ChuckJonas/vscode-apex-pmd/files/4382479/apex-pmd-java-test.zip)

the demo config `.vscode/settings.json`
