### ISSUE TITLE
apexPMD.runOnFileSave and apexPMD.runOnFileOpen - Java Not Suppert

### ISSUE THREAD

**Issue by rectcircle** [ChuckJonas/vscode-apex-pmd#75]
Hi, Your extension is very useful. I'm using your extension for Java code static checking. (By config `apexPMD.additionalClassPaths` and `apexPMD.rulesets` )

But I found that your code apexPMD.runOnFileSave and apexPMD.runOnFileOpen are limited to use only `const supportedLanguageCodes = ['apex', 'visualforce'] ;`

so, So I hope you can add Java language support. such as `src/extension.ts` Line: 10~11

```ts
const supportedLanguageCodes = ['apex', 'visualforce'];
const isSupportedLanguage = (langCode: string) => 0 <= supportedLanguageCodes.indexOf(langCode);
```

Thinks!

**Comment by ChuckJonas** [comment]
@rectcircle I built this with the intentions of only supporting Salesforce development (apex + visual force)...

However, several people have requested support of java, and technically there are only a few places that probably would need to be updated to support any language...  

The biggest reason I'm hesitant is the additional support that might require + lack of maintainers.  I don't personally do much java dev, so I would need to take take to setup some environments to test with.

If you want to zip up an example project where you've configured everything to work (included a ruleset and some sample java code that violates a rule or 2) then that would make it much easier to evaluate what it would take to add support.

**Comment by rectcircle** [comment]
@ChuckJonas These rules are very popular in the Chinese Java development community

to see https://github.com/alibaba/p3c and https://github.com/alibaba/p3c/tree/master/p3c-pmd 

demo [apex-pmd-java-test.zip](https://github.com/ChuckJonas/vscode-apex-pmd/files/4382479/apex-pmd-java-test.zip)

the demo config `.vscode/settings.json`
