### ISSUE TITLE
Java 8 is required to run Apex code PMD (contradicts with system requirements)

### ISSUE THREAD

**Issue by AndrewNR** [ChuckJonas/vscode-apex-pmd#81]
**Describe the bug**
Project readme file "System Requirements" section states that JRE 1.7 or higher is required for vscode-apex-pmd plugin to run. But the **pmd-apex-6.27.0.jar** Apex language rules plugin file is compiled with **Java 8**, thus cannot be run using Java 7.

My Path Java home is set to the JDK7:
```
> java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) Client VM (build 24.79-b02, mixed mode, sharing)
```

When I try to run the PMD for a given file in VSCode, it outputs `UnsupportedClassVersionError` error in the "Apex PMD" Output:
```
java.lang.UnsupportedClassVersionError: net/sourceforge/pmd/lang/apex/ApexLanguageModule : Unsupported major.minor version 52.0
```

**Apex PMD Output**

```
Analyzing c:\DEV\Projects\AO.Dev_dx1\force-app\main\default\classes\DCField.cls
stderr:Ignoring language for PMD: java.lang.UnsupportedClassVersionError: net/sourceforge/pmd/lang/apex/ApexLanguageModule : Unsupported major.minor version 52.0
stderr:

stderr:Unknown Language 'apex' for ruleExcessiveClassLength, supported Languages are vf

Failed Exit Code: 1
TypeError: Cannot read property 'includes' of undefined
TypeError: Cannot read property 'includes' of undefined
TypeError: Cannot read property 'includes' of undefined
. . . .
TypeError: Cannot read property 'includes' of undefined
0 issue(s) found
```

**Apex PMD Settings**

All standard settings (nothing changed since extension installation).

**Apex File**
Any Apex file.

**Versions (please complete the following information):**
 - OS: Windows 10
 - vscode: 1.49.1

------
**Potential workaround:**
Maybe can extract the JRE path into a setting, like `salesforce.salesforcedx-vscode-apex` plugin from Salesforce Extensions Pack does (see [Java Setup guide](https://developer.salesforce.com/tools/vscode/en/getting-started/java-setup))?

**Comment by ChuckJonas** [comment]
One of the recent PMD updates must have bumped the java req...

What you've proposed seems like the only reasonable solution...  



Wiring up a new configuration settings is pretty straight forward...  I'm less clear on the best way to use the new path...

Is it enough to just override `JAVA_HOME` on `process.env` when the value is present?

**Any interest in taking a stab at it?**

**Comment by AndrewNR** [comment]
I have just found [this line in the salesforce.salesforcedx-apex project](https://github.com/forcedotcom/salesforcedx-vscode/blob/0027280f1000972c2bcd020cbdf7b1ef2022794c/packages/salesforcedx-vscode-apex/src/languageServer.ts#L35), which is probably what does the thing. They prepend that `jrePath` to the `"/bin/java"`, in order to get the fully qualified path to the `java.exe` executable, so the command to run PMD process becomes smth like `<config.jrePath>/bin/java <params>`.

Maybe if this `jrePath` config variable is null/blank, it should be fine to run the PMD using just `java <params>` command, which would probably fall back to the default Java installed in the system (it is just like it works at the moment, right?).

I'm afraid I am not that good in Typescript to try fixing it...

**Comment by ChuckJonas** [comment]
@AndrewNR thanks, it's very helpful to see how they are doing it.

Instead of changing the `JAVA_HOME` env, it looks like they are just using the path to run the command.  Makes sense (I guess?).


I think I've got it coded up.  Can you install and test?

- unzip and Install [apex-pmd-0.5.3.vsix.zip](https://github.com/ChuckJonas/vscode-apex-pmd/files/5269412/apex-pmd-0.5.3.vsix.zip)  by running `Extension: Install from VSIX` from command pallet
- set `"apexPMD.jrePath": "/your/absolute/path/to/jre"`
- Make sure to reload the project

**Comment by AndrewNR** [comment]
Hey @ChuckJonas, just installed it from vsix and checked it locally.

1. I first checked that it is possible to run the PMD analysis if my Windows PATH variable uses Java 8 (`apexPMD.jrePath` was left blank). Works as expected.
2. Then I checked that if I switch the Windows PATH to use Java 7 and if I reload the VSCode, then PMD analysis stopped working (the original issue I described).
3. Then I set `apexPMD.jrePath` to my JRE8 installation absolute path: `apexPMD.jrePath = 'c:/java/jre8'`. With this, if I run "Apex Static Analysis: On File", PMD has successfully ran.

I believe that can be marked as resolved then. 👍  Good work man!

**Comment by ChuckJonas** [comment]
💯  

Thank you for the thoroughness in reporting and testing this. 

It makes maintaining OSS so much easier/enjoyable when people reporting issues take time to "contribute" to finding the solution instead of just demanding it gets fixed 🙏 

Will try to publish the fix ASAP

**Comment by Srid1014** [comment]
Hey @ChuckJonas iI'm new to this PMD. I have been trying to create custom rules for Apex pmd. I have followed the documentation but still i'm gettin Errors. For Example i have been trying to create rule to find whether the class name starts with P1. if it starts it must show an violation. can you please help me on this. maybe like step by step guide to create.

**Comment by adangel** [comment]
Hi @Srid1014 , which documentation did you follow? Which error exactly did you get?
Note: This repository is about the vscode-apex-pmd extension, not about PMD itself. Questions like "How do I ... with PMD?" are better asked in the [PMD Discussion](https://github.com/pmd/pmd/discussions) directly.
