### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by vbothrahorizontal** [ChuckJonas/vscode-apex-pmd#84]
- Issue Type: `Bug`
- Extension Name: `apex-pmd`
- Extension Version: `0.5.2`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ChuckJonas** [comment]
Can you please provide additional information?
