### ISSUE TITLE
rules set

### ISSUE THREAD

**Issue by jagz-pmd** [ChuckJonas/vscode-apex-pmd#85]
I do not see rules-set.xml file after i install Apex PMD plugin on VS Code

**Comment by ChuckJonas** [comment]
The ruleset is defaulted to [this file ](https://github.com/ChuckJonas/vscode-apex-pmd/blob/master/rulesets/apex_ruleset.xml).

If you want to change it, you can create a new ruleset and update the `apexPMD.rulesets` project or user setting (see the readme)
