### ISSUE TITLE
TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by benjaminloerincz** [ChuckJonas/vscode-apex-pmd#9]
I just installed pmd (v6.0.0) using homebrew, vscode (v1.19) and vscode-apex-pmd (v0.0.21) on mac os. Sadly, it doesn't work as expected. Here is the Apex PMD output log:

> PMD Command: java -cp "/usr/local/Cellar/pmd/6.0.0/libexec/lib/*" net.sourceforge.pmd.PMD -d "/Users/benjamin.loerincz/Documents/Test/vscodetestclass1.apex" -f csv -R "/Users/benjamin.loerincz/.vscode/extensions/chuckjonas.apex-pmd-0.0.21/rulesets/apex_ruleset.xml"
> error:null
> stdout:"Problem","Package","File","Priority","Line","Description","Rule set","Rule"
> 
> stderr:Dec 16, 2017 4:12:51 PM net.sourceforge.pmd.cache.NoopAnalysisCache <init>
> WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd/pmd_userdocs_getting_started.html#incremental-analysis
> 
> TypeError: Cannot read property 'substr' of undefined

**Comment by ChuckJonas** [comment]
Maybe try PMD 5.6?  I don't use this extension anymore so I'm not sure

**Comment by benjaminloerincz** [comment]
Should be fixed with https://github.com/ChuckJonas/vscode-apex-pmd/pull/10

**Comment by nchursin** [comment]
Fixed with #10 as expected
